apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  labels:
    app: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - image: jaegertracing/example-hotrod:latest
        name: hotrod
        args: ["all"]
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://jaeger:4318"
        ports:
          - containerPort: 8080
            name: frontend
          - containerPort: 8081
            name: customer
          - containerPort: 8082
            name: driver
          - containerPort: 8083
            name: route
        resources:
          limits:
            cpu: 200m
            memory: 200M
          requests:
            cpu: 100m
            memory: 100M
