apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: aggregated-trace-metrics
        static_configs:
          - targets: ['jaeger.default.svc.cluster.local:8889']
        metrics_path: /metrics
      - job_name: jaeger-metrics
        static_configs:
          - targets: ['jaeger:8889']
        metrics_path: /metrics
